/**
 * Created by KING on 2017/8/22.
 */
export const FETCH_DATA_REQUEST = 'FETCH_FOLLOW_PARTY_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_FOLLOW_PARTY_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_FOLLOW_PARTY_DATA_FAILURE';