/**
 * Created by KING on 2017/8/27.
 */
export const FETCH_DATA_REQUEST = 'FETCH_VIDEO_DETAIL_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_VIDEO_DETAIL_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_VIDEO_DETAIL_DATA_FAILURE';