/**
 * Created by KING on 2017/8/29.
 */
export const FETCH_DATA_REQUEST = 'FETCH_VIDEO_LIST_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_VIDEO_LIST_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_VIDEO_LIST_DATA_FAILURE';